## AWS parameters
kubectl_context_name: "aws-eks-dev"

## Jenkins parameters
jenkins_base_url: "jenkins-test.example.com"

jenkins_install_plugins:
  - kubernetes:1.56.2

jenkins_approved_signatures:
  - "method java.lang.Class isInstance java.lang.Object"

ingress:
  enabled: yes
  class_name: alb
  annotations: 
    external-dns.alpha.kubernetes.io/hostname: "{{ jenkins_base_url }}"
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/certificate-arn: "CHANGEME"
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    

jenkins_agent_pod_templates:
   python: |
      - name: python
        label: python
        serviceAccount: jenkins
        containers:
          - name: python
            image: python:3
            command: '/bin/sh -c'
            args: 'cat'
            ttyEnabled: true
            privileged: true
            resourceRequestCpu: '400m'
            resourceRequestMemory: '512Mi'
            resourceLimitCpu: '1'
            resourceLimitMemory: '1024Mi'



