---
jenkins_chart_version: "4.2.17"
jenkins_namespace: "jenkins"

jenkins_controller_image_tag: "2.377"
jenkins_controller_image_pull_policy: "IfNotPresent"

jenkins_agent_image_tag: "latest"

jenkins_admin_email: "example@mail.com"
jenkins_base_url: "jenkins-test.example.com"

jenkins_req_cpu: "1"
jenkins_req_mem: "2Gi"
jenkins_lim_cpu: "2"
jenkins_lim_mem: "3Gi"

jenkins_additional_plugins: {}
jenkins_agent_pod_templates: {}
jenkins_approved_signatures: []

pipeline_name: "demo-pipeline"
pipeline_git_url:  "https://github.com/nickyfoster/jenkins-helm-ansible-tutorial.git"
pipeline_git_branch: "main"
pipeline_git_creds: ""
pipeline_jenkinsfile_path: "Jenkinsfile"

ingress:
  enabled: yes
  class_name: nginx
  annotations: 
    kubernetes.io/ingress.class: "nginx"